Dockerfile: Do not set entrypoint to python
I believe that using python as an entrypoint does not provide
benefits for our situation, however it leads to interesting issues
like these:

    $ docker run --rm -ti rotebeete/juntagrico /bin/sh
      File "/bin/sh", line 1
    SyntaxError: Non-UTF-8 code starting with '\xaa' in file /bin/sh
    on line 2, but no encoding declared;
    see http://python.org/dev/peps/pep-0263/ for details